### ISSUE TITLE
Exercise detail modal

### ISSUE THREAD

**Issue by MDaniel96** [MDaniel96/training-app#11]

**Comment by akos989** [comment]
.json és model-ba video

**Comment by akos989** [comment]
- [x] fehér mód színek
- [x] androidon látszik video jel (poster="noposter")
- [x] a videóra fade in legyen (animation/fold mintájára)
- [x] description-nél kisebb szöveg
- [x] badge legkerekítés
- [x] fehér módban pagination
- [ ] description felfelé görgetésnél ne görögjön a modal
- [x] assests/images => assets/image (külön mappa)
- [x] videók az instáról
- [x] description a jsonbe
- [x] equipmenthez kis icon
